[font]
size = 8.0

[font.normal]
family = "MononokiNerdFontMono"
style = "regular"

[font.offset]
x = 0
y = 0

[window]

[colors.primary]
background = '#191724'
foreground = '#e0def4'

[colors.cursor]
text = '#e0def4'
cursor = '#524f67'

[colors.vi_mode_cursor]
text = '#e0def4'
cursor = '#524f67'

[colors.selection]
text = '#e0def4'
background = '#403d52'

[colors.normal]
black = '#26233a'
red = '#eb6f92'
green = '#31748f'
yellow = '#f6c177'
blue = '#9ccfd8'
magenta = '#c4a7e7'
cyan = '#ebbcba'
white = '#e0def4'

[colors.bright]
black = '#6e6a86'
red = '#eb6f92'
green = '#31748f'
yellow = '#f6c177'
blue = '#9ccfd8'
magenta = '#c4a7e7'
cyan = '#ebbcba'
white = '#e0def4'

[colors.hints]
start = {foreground = '#908caa', background = '#1f1d2e' }
end = { foreground = '#6e6a86', background = '#1f1d2e' }

# Colors (Gruvbox dark)

# Default colors
#  [colors.primary]
#  # hard contrast background = = '#1d2021'
#  # background = '#282828'
#  background = '#141617'
#  # soft contrast background = = '#32302f'
#  foreground = '#ebdbb2'
#  
#  # Normal colors
#  [colors.normal]
#  black   = '#282828'
#  red     = '#cc241d'
#  green   = '#98971a'
#  yellow  = '#d79921'
#  blue    = '#458588'
#  magenta = '#b16286'
#  cyan    = '#689d6a'
#  white   = '#a89984'
#  
#  # Bright colors
#  [colors.bright]
#  black   = '#928374'
#  red     = '#fb4934'
#  green   = '#b8bb26'
#  yellow  = '#fabd2f'
#  blue    = '#83a598'
#  magenta = '#d3869b'
#  cyan    = '#8ec07c'
#  white   = '#ebdbb2'
